name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install -r requirements.txt
    - uses: ankane/setup-postgres@v1
      with:
        database: pgvector_python_test
    - run: |
        sudo apt-get update && sudo apt-get install postgresql-server-dev-14
        cd /tmp
        git clone --branch v0.2.1 https://github.com/ankane/pgvector.git
        cd pgvector
        make
        sudo make install
    - run: pytest
